name: jenkins-docker

services:
  agent:
    container_name: jenkins-agent1
    image: jenkins/inbound-agent:alpine
    restart: unless-stopped
    privileged: true
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_URL: ${JENKINS_MASTER_URL:-http://jenkins:8080}
      JENKINS_AGENT_NAME: agent1
      JENKINS_SECRET: ${JENKINS_AGENT_SECRET:-MOxEgYvvr6pG8iQ5KzBzaWFxMOn+KqKtFALII3lTh7+Cxz9uQFVbQUt4Tb6tQ58i}
