name: jenkins-docker

services:
  agent:
    container_name: jenkins-agent1
    image: jenkins/inbound-agent:alpine
    restart: unless-stopped
    privileged: true
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_URL: ${AGENT_JENKINS_URL:-http://jenkins:8080}
      JENKINS_AGENT_NAME: agent1
      JENKINS_SECRET: ${AGENT_JENKINS_SECRET1}
