version: '3.3'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - ${JENKINS_PORT:-0.0.0.0:8080}:8080
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    environment:
      JENKINS_OPTS: ${JENKINS_OPTS:-}

  agent1:
    container_name: agent1-jenkins
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    expose:
      - 22
    environment:
      JENKINS_AGENT_SSH_PUBKEY: ${AGENT1_RSA:-}

  agent2:
    container_name: agent2-jenkins
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    expose:
      - 22
    environment:
      JENKINS_AGENT_SSH_PUBKEY: ${AGENT2_RSA:-}
