name: jenkins-docker

networks:
  network-app:
    name: network-jenkins
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET:-10.210.15.0/25}

services:
  jenkins:
    container_name: jenkins-master
    image: jenkins/jenkins:lts
    restart: unless-stopped
    privileged: true
    user: root
    networks:
      network-app:
    ports:
      - ${JENKINS_PORT:-0.0.0.0:8080}:8080
      - ${JENKINS_PORT_CONNECTOR:-0.0.0.0:50000}:50000
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_OPTS: ${JENKINS_OPTS:-}

  agent1:
    extends:
      file: 01-agent.yml
      service: agent
    container_name: jenkins-agent1
    networks:
      network-app:
    environment:
      JENKINS_AGENT_NAME: agent1
      JENKINS_SECRET: ${AGENT_JENKINS_SECRET1}
