version: '3.3'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - ${JENKINS_PORT:-0.0.0.0:8080}:8080
      - ${JENKINS_PORT_CONNECTOR:-0.0.0.0:50000}:50000
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      JENKINS_OPTS: ${JENKINS_OPTS:-}

  agent1:
    container_name: agent1-jenkins
    image: villcabo/jenkins-ssh-agent-custom
    privileged: true
    user: root
    expose:
      - 22
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_AGENT_SSH_PUBKEY: ${AGENT_RSA}

  agent2:
    container_name: agent2-jenkins
    image: villcabo/jenkins-ssh-agent-custom
    privileged: true
    user: root
    expose:
      - 22
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_AGENT_SSH_PUBKEY: ${AGENT_RSA}
